language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pacog/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pacog/react-test npm test

after_success:
  - docker build -t pacog/multi-client ./client
  - docker build -t pacog/multi-nginx ./nginx
  - docker build -t pacog/server ./server
  - docker build -t pacog/worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pacog/multi-client
  - docker push pacog/multi-nginx
  - docker push pacog/multi-server
  - docker push pacog/multi-worker



